[server]
protocol = http
host = 0.0.0.0
port = 8989
daemon = false
log_file = /var/log/ivclock/ivclock.log
log_level = info
auth_user = ivdevice_admin
auth_pass = super_secure_pass_123

[influxdb]
url = http://127.0.0.1:8086
token = YOUR_INFLUXDB_SECRET_TOKEN==
org = my_org
bucket = esp32_data
